### ISSUE TITLE
Add a license to the repository

### ISSUE THREAD

**Issue by cbjuan** [S-CHOI-S/Quantum-Qiskit#1]
I recently came across your project Quantum-Qiskit and I noticed that the repository github.com/S-CHOI-S/Quantum-Qiskit currently does not have a license specified.

Why Adding a License is Important?

As [GitHub documents](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository)
>Public repositories on GitHub are often used to share open source software. For your repository to truly be open source, you'll need to license it so that others are free to use, change, and distribute the software.

Would be possible to add a valid license to this repository? Probably something really OpenSource such as the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0) would fit really well.

Thanks!

**Comment by S-CHOI-S** [comment]
Hello,

Thank you for your interest in my project Quantum-Qiskit and for pointing out the important issue regarding the license.

As you mentioned, specifying a license is crucial for open-source projects. Since this is a solo project, I understand that adding a license will help others use, modify, and contribute to the project more freely.

I will look into adding the Apache 2.0 license to make the project fully open-source. I appreciate your suggestion and will ensure that a license is added soon.

Thanks again for your valuable input, and I hope the project will be useful to others.

Best regards,

**Comment by cbjuan** [comment]
Thanks
